# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: 反省自己:每天要做有意义的事情！
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: MusicPlayer
  works_url: /
- works_name: WeiBo
  works_url: /atom.xml

#duoshuo 
duoshuo: yachaocn

# Miscellaneous
github: https://github.com/yachaocn
twitter: https://twitter.com/
facebook: https://www.facebook.com/yachao.zhang.39
google: https://plus.google.com/115506244189928287258/posts
weibo: http://weibo.com/5586290583/profile?topnav=1&wvr=6

#about  timeline
timeline:
- num: 1
  word: 2015/04/11-搭建Hexo开始我的博客之旅，域名：http://yachaocn.com/
#- num: 2
#  word: 2014/11/29-XXX你好啊
#- num: 3
#  word: 2015/02/18-DDD你是什么
#- num: 4
#  word: More

#Links
links:
- name: ╅→敏 
  link: http://flolangka.com
- name: ⒎過客ㄞ
  link: http://cocoyous.com
- name: kieran
  link: http://go.kieran.top
- name: zhaofei
  link: http://zhaofei.tk/archives/
- name: Andrew Liu
  link: http://andrewliu.tk
- name: 兰江老涌
  link: http://lxy361.tk/2014/10/28/Hexo-主题修改教程/
- name: ibruce
  link: http://ibruce.info/2013/11/22/hexo-your-blog/

#widgets
widgets:
- category
- search
- tagcloud  #标签云
- intro
- weibo    
- blogroll    #友情链接
